POST http://localhost:8080/api/artists
Content-Type: application/json


{
    "pseudo": "pseudotestRegion3",
    "name": "nametesteeRegion",
    "firstName" :"firstnametestRegion",
    "birthdate": "1999-01-01",
    "image": "zezetzetzt",
    "bio": "trucbidulechose lorem blablabalbalb voir si la région se crée",
    "email": "test@testregion.com",
    "phone": 664646421,
    "address": "5 rue machin du truc",
    "category": [3],
    "region": 6
}