POST http://localhost:8080/api/organizers
//POST http://baptistequeyssac-server.eddi.cloud/projet-01-comedy-among-other-things-back/public/api/organizers
Content-Type: application/json

{
    "name": "tutuegrrrerehteut",
    "address": "5 rue machincrrrehose",
    "phone": 678543624,
    "status": 5,
    "type": true,
    "region": 12,
    "user": 14
    
    
}