POST http://localhost:8080/api/organizers
Content-Type: application/json


{
  "name" : "testnameOrganizer",
  "address": "6 rue de la belle avenue",
  
  "description": "Organize des évenements de styles stand-up au Club À Gogo",
  "region": "Normandie",
  "logo": "blablabla",
  "email":"truc@bidule.com",
  "phone": 684532170
  
  
}