POST http://localhost:8080/api/artists
Content-Type: application/json


{
    "pseudo": "pseudotestee",
    "name": "nametestee",
    "firstName" :"firstnametest",
    "birthdate": "1999-01-01",
    "image": "zezetzetzt",
    "bio": "trucbidulechose lorem blablabalbalb",
    "email": "test@test.com",
    "phone": 664646421,
    "address": "5 rue machin du truc",
    "region": {
        "id": 12,
        "name": "Pays de la Loire"
    } 
}