POST http://localhost:8080/api/events
Content-Type: application/json
Authorization: Bearer MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyAdL/376JzKUgvzmcPMCxvVP88c6a81i9mxtdEAnhN1catesPt19ZoGxykOn+mD5rMI2T50+eQxhB8CeMy2oBI2xixm7/lCsoRJHDhgteo9OfkVsEC8QFg1LGWurqevv7V9LYQEcB6bymF++jTe2jaFaGn3pNxPNs1wlNj0MY25f19V8e+srQdZXpOIjOSc4Y3eGFzDMvQBxFiXMUnXpqkoxYUfR6OrTlD+cz/4uhLwSEAcflk6kDet9jBgA4X6JahjtPPBpcwynI/FLOTdi49awv+41Zf2Vp4smJYZmoLUYk9gIhkyvwlUJCnfLaEHTxW1zNHUB1exoP1qLvLqNzwIDAQAB

{
    "title": "Club À Gogo",
    "duration": 10,
    "address" :"4 rue du biniou",
    "price": 5,
    "summary": "Venez nombreux blablabla",
    "poster": "zzzzzzzzz",
    "date": "10-04-2023",
    "info": "blabla",
    "frequency": "régulière",
    "region_id": 3,
    "type_id": 2,
    "createdAt": "2023-04-06"
   
    
}