GET http://localhost:8080/api/organizers
Authorization: Bearer MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyAdL/376JzKUgvzmcPMCxvVP88c6a81i9mxtdEAnhN1catesPt19ZoGxykOn+mD5rMI2T50+eQxhB8CeMy2oBI2xixm7/lCsoRJHDhgteo9OfkVsEC8QFg1LGWurqevv7V9LYQEcB6bymF++jTe2jaFaGn3pNxPNs1wlNj0MY25f19V8e+srQdZXpOIjOSc4Y3eGFzDMvQBxFiXMUnXpqkoxYUfR6OrTlD+cz/4uhLwSEAcflk6kDet9jBgA4X6JahjtPPBpcwynI/FLOTdi49awv+41Zf2Vp4smJYZmoLUYk9gIhkyvwlUJCnfLaEHTxW1zNHUB1exoP1qLvLqNzwIDAQAB